<a href="https://colab.research.google.com/github/hugoshiroma/IA-MLP-2/blob/master/EP2IA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#!/usr/bin/python

import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import numpy as np
import pandas as pd

df = pd.read_csv('caracteres-limpos.csv', header=None)
train_df = df.drop(labels=63, axis=1)
x_data = np.array(train_df)

print(x_data)

[[-1 -1  1 ...  1  1  1]
 [ 1  1  1 ...  1  1 -1]
 [-1 -1  1 ...  1  1 -1]
 ...
 [ 1  1  1 ...  1  1  1]
 [-1 -1 -1 ...  1 -1 -1]
 [ 1  1  1 ... -1  1  1]]
